import { redactHarnessSecrets } from "@/core/harness/security";
import { NotebookBridgePreflightError, notebookBridgePreflightMessage } from "@/core/harness/server/bridge-preflight";
import { verifyDshCurrentRunEvidence, verifyDshReadonlyAnswer, type DshAnalysisToolAttempt, type DshReadonlyObservation } from "./readonly-answer";

/** Missing capabilities may disable the business plugin, not disable chatting.
 * Identity, invalid scope, attachment mismatches and unknown errors remain hard
 * failures; no raw exception or untrusted exception.name is accepted here.
 */
export function dshConversationCapabilityNotice(error: unknown): string | undefined {
  if (!(error instanceof NotebookBridgePreflightError) || ![
    "missing_notebook_context", "missing_data_context", "unsupported_task_context",
    "semantic_model_unavailable", "notebook_cell_unsupported", "python_unavailable",
  ].includes(error.code)) return;
  return notebookBridgePreflightMessage(error);
}

export function dshConversationNeedsDraft(attempts: readonly DshAnalysisToolAttempt[]): boolean {
  return attempts.some(attempt => attempt.toolName === "editNotebookCells" || attempt.toolName === "submitNotebookDraft");
}

interface ConversationDeliveryInput {
  finalResponse?: string;
  formalUnchanged: boolean;
  attempts: readonly DshAnalysisToolAttempt[];
  observations: readonly DshReadonlyObservation[];
  parameterCellIds: readonly string[];
  /** Captured from the original request, not from model output. */
  baseRevision?: number;
}

export interface DshConversationDelivery {
  valid: boolean;
  message: string;
  issue: string;
  evidenceIds: string[];
  /** Conversation delivery is not a fabricated successful data verification. */
  kind: "conversation" | "toolInformation" | "notebookEvidence";
}

/** Select a terminal from private tool behavior, never user-text keywords or a
 * model-declared success label. This is receipt validation, not a proof of the
 * semantic truth of every sentence generated by the model.
 */
export function verifyDshConversationDelivery(input: ConversationDeliveryInput): DshConversationDelivery {
  const fail = (issue: string): DshConversationDelivery => ({ valid: false, issue, message: "", evidenceIds: [], kind: "conversation" });
  if (!input.formalUnchanged) return fail("正式 Notebook 或看板发生变化，拒绝对话交付。");
  if (typeof input.finalResponse !== "string" || !input.finalResponse.trim()) return fail("DSH 没有返回有效答复。");
  if (dshConversationNeedsDraft(input.attempts)) return fail("修改任务必须取得已验证的成功草稿，不能用聊天代替。");
  let searchNeedsRecovery = false;
  for (const attempt of input.attempts) {
    if (attempt.status === "running") return fail("仍有工具未结束，不能交付对话。");
    if (attempt.status === "failure") {
      if (attempt.toolName !== "cellSearch" || !attempt.recoverableSearchFailure) return fail("本轮业务工具执行失败，不能宣告分析成功。");
      searchNeedsRecovery = true;
    } else if (attempt.toolName === "cellSearch") searchNeedsRecovery = false;
  }
  if (searchNeedsRecovery) return fail("本轮检索尚未恢复，不能仅凭最终文本宣告成功。");
  const answer = redactHarnessSecrets(input.finalResponse.trim());
  const notebookObservations = input.observations.filter(observation => ["cellSearch", "runNotebookCells"].includes(observation.toolName));
  if (notebookObservations.length) {
    const ran = input.attempts.some(attempt => attempt.toolName === "runNotebookCells");
    if (ran) {
      const evidence = verifyDshCurrentRunEvidence({ observations: notebookObservations,
        baseRevision: input.baseRevision, parameterCellIds: input.parameterCellIds });
      return { ...evidence, kind: "notebookEvidence", message: evidence.valid
        ? `只读回答：依据本轮成功运行的结果，范围以实际返回数据为准；未修改步骤或看板。\n${answer}` : "" };
    }
    const result = verifyDshReadonlyAnswer({ mode: { allowRun: false, requireOutput: false }, finalResponse: answer,
      observations: notebookObservations, formalUnchanged: input.formalUnchanged, failedTools: [],
      parameterCellIds: input.parameterCellIds });
    return { ...result, kind: "notebookEvidence" };
  }
  const allowedInformation = new Set(["getKernelPackagesInfo", "inspectEdsRawWorkbook", "readEdsRawRows", "inspectConnectionSchema"]);
  if (input.attempts.some(attempt => !allowedInformation.has(attempt.toolName))) return fail("对话使用了未经允许的业务操作。");
  if (input.observations.length !== input.attempts.length) return fail("工具尝试与实际读取回执不一致。");
  const observed = input.observations.length > 0;
  const notice = observed
    ? "本轮仅完成工具信息读取，未验证分析计算或修改正式文档。"
    : "本轮为对话回复，未读取或计算数据，也未修改正式文档。";
  return { valid: true, message: `${answer}\n\n${notice}`, issue: "",
    evidenceIds: input.observations.map(observation => observation.toolCallId).slice(-15),
    kind: observed ? "toolInformation" : "conversation" };
}
